# Generated by Django 4.0.3 on 2022-04-09 04:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_img', models.ImageField(upload_to='images', verbose_name='投稿画像')),
                ('posted_at', models.DateTimeField(auto_now_add=True, help_text='投稿日', verbose_name='投稿日')),
                ('text', models.CharField(max_length=255, verbose_name='本文')),
                ('good', models.IntegerField(default=0, verbose_name='いいねの数')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('posted_at', models.DateTimeField(auto_now_add=True, help_text='投稿日', verbose_name='コメント投稿日')),
                ('text', models.CharField(max_length=255, verbose_name='本文')),
                ('good', models.IntegerField(default=0, verbose_name='いいねの数')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_app.post', verbose_name='コメント投稿先')),
            ],
        ),
    ]
